"use strict";
exports.__esModule = true;
var superHeros = [];
var heroPower = [];
superHeros.push("spiderman");
heroPower.push(2);
var allUsers = [];
allUsers.push({ name: "", isActive: true });
var colorCodes = [];
colorCodes.push([255, 0, 255], [255, 255, 0]);
